# Generated by Django 3.2.4 on 2021-07-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('nomeSoftware', models.CharField(max_length=20)),
                ('descrizioneSoftware', models.CharField(max_length=100)),
            ],
        ),
    ]
