# Generated by Django 3.2.4 on 2021-07-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrizioneSoftware',
            new_name='descrizione_Software',
        ),
    ]
