# Generated by Django 3.2.4 on 2021-07-31 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_descrizionesoftware_post_descrizione_software'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrizione_Software',
            new_name='descrizione_Box',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nomeSoftware',
            new_name='nomeSocial',
        ),
    ]
